[project]
name = "mini-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
	"browser-use>=0.5.9",
	"browser-use-sdk>=3.7.1",
	"croniter>=6.2.4",
	"discord>=2.3.2",
	"dotenv>=0.9.9",
	"fastapi>=0.116.0",
	"google-genai>=2.7.0",
	"langchain-google-genai>=4.2.4",
	"mcp>=1.27.2",
	"openai>=2.38.0",
	"sqlalchemy>=2.0.50",
	"uvicorn>=0.35.0",
]
