CREATE TABLE worker_conversations (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    session_id  TEXT NOT NULL UNIQUE,  -- generated by us, passed to Claude Code via --session-id
    description TEXT NOT NULL,
    cwd         TEXT NOT NULL,  -- Claude Code can only resume a session from the directory it started in
    status      TEXT NOT NULL DEFAULT 'idle'
                CHECK (status IN ('running', 'idle', 'error')),
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_used   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE worker_messages (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    conversation_id INTEGER NOT NULL
                    REFERENCES worker_conversations(id) ON DELETE CASCADE,
    type            TEXT NOT NULL
                    CHECK (type IN ('prompt', 'assistant', 'tool_result', 'system', 'result')),
    text            TEXT,          -- plain text for display/search
    raw             TEXT NOT NULL, -- the full message JSON as Claude Code sent it
    message_uuid    TEXT UNIQUE,   -- Claude Code's message uuid, for de-duplication
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_worker_messages_conversation ON worker_messages (conversation_id, id);
